### ISSUE TITLE
🎃 Improve Navbar

### ISSUE THREAD

**Issue by tinarskii** [urgrowth/urgrowth-web-frontend#6]
## Details

Current one is a cluttered mess and hard to navigate, perhaps make it tidier.

## What's the benefit? 

- Accessibility
- Elegant
- Riko will find her mom

## More information

- The Egyptians believed the most significant thing you could do in your life, was die.

**Comment by AruchaK** [comment]
ayo bro I would like to do this
also do you have design in your mind?

**Comment by tinarskii** [comment]
> ayo bro I would like to do this also do you have design in your mind?

Currently not 😭🥺

**Comment by AruchaK** [comment]
aw man okay, I will try to see what I can you

**Comment by tinarskii** [comment]
> aw man okay, I will try to see what I can you

appreciate it🥺

**Comment by tinarskii** [comment]
Fixed by #11
