### ISSUE TITLE
🎃 Add CREDITS page

### ISSUE THREAD

**Issue by tinarskii** [urgrowth/urgrowth-web-frontend#7]
## Details

What are you gonna do about it? SUE ME

For legal reasons, the text above is a joke. Please do not sue me. I beg you.

BTW all icons credits are in `~/public/credits` file, you may turn it into JSON

## What's the benefit?

- I WON'T GET SUED

## More information

- Ralsei

**Comment by vaibhavj2111** [comment]
Hey, I am a newbie and a little confused. So in this issue, do we only need to turn the ~/public/credits into a json file or we also have to implement it to the main webpage also??

**Comment by tinarskii** [comment]
> Hey, I am a newbie and a little confused. So in this issue, do we only need to turn the ~/public/credits into a json file or we also have to implement it to the main webpage also??

you could, and the main thing here is to create a `/credit` page
so you may do it anyway you want.
(just so i wont get sued)😭
